# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agentbox < Formula
  desc "CLI for running AI agents inside an isolated Docker container"
  homepage "https://github.com/aleksey925/agentbox"
  version "0.13.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aleksey925/agentbox/releases/download/v0.13.0/agentbox_0.13.0_darwin_amd64.tar.gz"
      sha256 "5721c8f6c5897eb5a6625aed7cade8dc95672b3e13e086d89249f2895867e2e7"

      def install
        bin.install "agentbox"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aleksey925/agentbox/releases/download/v0.13.0/agentbox_0.13.0_darwin_arm64.tar.gz"
      sha256 "1db8b3801c9e7d9a34d7867fb58c48316a804a508c0abcdfeb6cd380d25474b6"

      def install
        bin.install "agentbox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aleksey925/agentbox/releases/download/v0.13.0/agentbox_0.13.0_linux_amd64.tar.gz"
      sha256 "2782d60e963d6269013d3a86c309b8cd24c9a119b644344b77b949eca4cc05dd"
      def install
        bin.install "agentbox"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aleksey925/agentbox/releases/download/v0.13.0/agentbox_0.13.0_linux_arm64.tar.gz"
      sha256 "c71707fa9db1ed8781d1dea39023081190bbbbef5475aa752ce9f151c969932b"
      def install
        bin.install "agentbox"
      end
    end
  end

  def caveats
    <<~EOS
      If you previously installed agentbox manually (e.g. to ~/.local/bin),
      remove that copy to avoid PATH conflicts:
        rm ~/.local/bin/agentbox
    EOS
  end
end
