# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agentbox < Formula
  desc "CLI for running AI agents inside an isolated Docker container"
  homepage "https://github.com/aleksey925/agentbox"
  version "0.11.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aleksey925/agentbox/releases/download/v0.11.0/agentbox_0.11.0_darwin_amd64.tar.gz"
      sha256 "61d26c3dfa2c4eaab2037a1502b6e582c8c8321da9d642c2f947ef983bd81524"

      def install
        bin.install "agentbox"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aleksey925/agentbox/releases/download/v0.11.0/agentbox_0.11.0_darwin_arm64.tar.gz"
      sha256 "4ed08f642cca31af92593902a99c5699abab0cb2df4cc7c714ad9b52e35ae8e3"

      def install
        bin.install "agentbox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aleksey925/agentbox/releases/download/v0.11.0/agentbox_0.11.0_linux_amd64.tar.gz"
      sha256 "fd57cbe60d9d55dffab81e1e5cd7042e9fba68a4be64dbd2942bef7400004cad"
      def install
        bin.install "agentbox"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aleksey925/agentbox/releases/download/v0.11.0/agentbox_0.11.0_linux_arm64.tar.gz"
      sha256 "7a5ed417310ededa8881bea45b321af766e6b830cb41bd7edba5325fba49a1f3"
      def install
        bin.install "agentbox"
      end
    end
  end

  def caveats
    <<~EOS
      If you previously installed agentbox manually (e.g. to ~/.local/bin),
      remove that copy to avoid PATH conflicts:
        rm ~/.local/bin/agentbox
    EOS
  end
end
