# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KafkaTui < Formula
  desc "k9s-style terminal UI to browse, manage, and configure Apache Kafka"
  homepage "https://github.com/aleksey925/kafka-tui"
  version "0.9.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aleksey925/kafka-tui/releases/download/v0.9.0/kafka-tui_0.9.0_darwin_amd64.tar.gz"
      sha256 "ba272c877150652ee78208aeebf5c3c729214673dadac0bec3ba79832d071f06"

      def install
        bin.install "kafka-tui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aleksey925/kafka-tui/releases/download/v0.9.0/kafka-tui_0.9.0_darwin_arm64.tar.gz"
      sha256 "0fa5cd04ba72d836caf8fa43e95cf628d7de1b4f2d1864b297a72ab9cac48f6f"

      def install
        bin.install "kafka-tui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aleksey925/kafka-tui/releases/download/v0.9.0/kafka-tui_0.9.0_linux_amd64.tar.gz"
      sha256 "60d3011c238ebdc9bacd2bfe89f602b40e250d9466df08adb71cb6aa98490ab7"
      def install
        bin.install "kafka-tui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aleksey925/kafka-tui/releases/download/v0.9.0/kafka-tui_0.9.0_linux_arm64.tar.gz"
      sha256 "302803859522f675b7c9f0872d37c4c0c29dc5911d477a5f88f9a16b9df59609"
      def install
        bin.install "kafka-tui"
      end
    end
  end

  def caveats
    <<~EOS
      If you previously installed kafka-tui manually (e.g. to ~/.local/bin),
      remove that copy to avoid PATH conflicts:
        rm ~/.local/bin/kafka-tui
    EOS
  end
end
