# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KafkaTui < Formula
  desc "k9s-style terminal UI to browse, manage, and configure Apache Kafka"
  homepage "https://github.com/aleksey925/kafka-tui"
  version "0.10.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aleksey925/kafka-tui/releases/download/v0.10.0/kafka-tui_0.10.0_darwin_amd64.tar.gz"
      sha256 "f5756178b40087c51ce91b74bd6a5ccfa8bd2de3fc6dcf875dc3c26b1050b8a8"

      def install
        bin.install "kafka-tui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aleksey925/kafka-tui/releases/download/v0.10.0/kafka-tui_0.10.0_darwin_arm64.tar.gz"
      sha256 "32df1258e8c821b7455d2b3766b224a244aa46734683b32a7c356d17d3b30366"

      def install
        bin.install "kafka-tui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aleksey925/kafka-tui/releases/download/v0.10.0/kafka-tui_0.10.0_linux_amd64.tar.gz"
      sha256 "8040c212a4e3bdf82dc71dd70f571b764943537c06702fb270bd7e3608bfa52b"
      def install
        bin.install "kafka-tui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aleksey925/kafka-tui/releases/download/v0.10.0/kafka-tui_0.10.0_linux_arm64.tar.gz"
      sha256 "b3f18ef672e48474ffe0b712bf7111a76114c6fe27c3ef222cbe3c993b212d91"
      def install
        bin.install "kafka-tui"
      end
    end
  end

  def caveats
    <<~EOS
      If you previously installed kafka-tui manually (e.g. to ~/.local/bin),
      remove that copy to avoid PATH conflicts:
        rm ~/.local/bin/kafka-tui
    EOS
  end
end
